default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host_postgres'] %>
  port: <%= ENV['port_postgres'] %>
  username: <%= ENV['username_postgres'] %>
  password: <%= ENV['password_postgres'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: authentication_development

test:
  <<: *default
  database: authentication_test

production:
  <<: *default
  database: authentication_production
  username: authentication
  password: <%= ENV['authentication_DATABASE_PASSWORD'] %>